services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Live code reload
      - /app/node_modules # Prevent host overwrite
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_SECRET_SALT=${AUTH_SECRET_SALT}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_PASS=${EMAIL_PASS}
    env_file:
      - .env
